version: '3.8'

services:

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:3.4'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  db-client-postgres:
    image: postgres:latest
    container_name: postgres-hotel
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: coti
      POSTGRES_DB: hotel-management-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  db-review-mongodb:
    image: mongo:latest
    container_name: mongodb-review
    ports:
      - "27017:27017"
    volumes:
      - mongodb1-data:/data/db
    networks:
      - my_network

  db-customer-mongodb:
    image: mongo:latest
    container_name: mongodb-customer
    ports:
      - "27018:27017"
    volumes:
      - mongodb2-data:/data/db
    networks:
      - my_network

networks:
  broker-kafka:
    driver: bridge
  my_network:
    driver: bridge

volumes:
  postgres_data:
  mongodb1-data:
  mongodb2-data:
